### ISSUE TITLE
ERROR: AddressSanitizer: SEGV on unknown address 0x000000000030 

### ISSUE THREAD

**Issue by alvin1221** [nanomq/NanoNNG#283]
**Describe the bug**
Crash after connection was established;

**Expected behavior**

**Actual Behavior**
Describe what occurred.

**To Reproduce**
Use nanomq to create bridge connection of mqtt-quic;
`bridge.mqtt.emqx.keepalive=10;`

** Environment Details **
 - NanoMQ version
 - Operating system and version
 - Compiler and language used
 - testing scenario

**Client SDK**
If possible include the mqtt sdk you used to connect to nanomq
Minimal C test cases are perferred.

**Additional context**

log:
```bash
2022-09-14 17:03:37 [435930] INFO  ../nng/src/supplemental/quic/quic_api.c:307  QuicConnectionCallback: QuicConnectionCallback triggered! 10
2022-09-14 17:03:37 [435930] WARN  ../nng/src/supplemental/quic/quic_api.c:412  QuicConnectionCallback: QUIC_CONNECTION_EVENT_DATAGRAM_STATE_CHANGED
2022-09-14 17:03:37 [435930] INFO  ../nng/src/supplemental/quic/quic_api.c:307  QuicConnectionCallback: QuicConnectionCallback triggered! 0
2022-09-14 17:03:37 [435930] INFO  ../nng/src/supplemental/quic/quic_api.c:312  QuicConnectionCallback: [conn][0x61f000000080] Connected

2022-09-14 17:03:37 [435930] INFO  ../nng/src/supplemental/quic/quic_api.c:307  QuicConnectionCallback: QuicConnectionCallback triggered! 7
2022-09-14 17:03:37 [435930] INFO  ../nng/src/supplemental/quic/quic_api.c:415  QuicConnectionCallback: QUIC_CONNECTION_EVENT_STREAMS_AVAILABLE
2022-09-14 17:03:37 [435930] INFO  ../nng/src/supplemental/quic/quic_api.c:307  QuicConnectionCallback: QuicConnectionCallback triggered! 7
2022-09-14 17:03:37 [435930] INFO  ../nng/src/supplemental/quic/quic_api.c:415  QuicConnectionCallback: QUIC_CONNECTION_EVENT_STREAMS_AVAILABLE
2022-09-14 17:03:37 [435930] INFO  ../nng/src/supplemental/quic/quic_api.c:307  QuicConnectionCallback: QuicConnectionCallback triggered! 9
2022-09-14 17:03:37 [435930] INFO  ../nng/src/supplemental/quic/quic_api.c:418  QuicConnectionCallback: QUIC_CONNECTION_EVENT_IDEAL_PROCESSOR_CHANGED
2022-09-14 17:03:37 [435930] WARN  ../nng/src/supplemental/quic/quic_api.c:286  QuicStreamCallback: QUIC_STREAM_EVENT_START_COMPLETE
2022-09-14 17:03:38 [435930] INFO  ../nng/src/supplemental/quic/quic_api.c:307  QuicConnectionCallback: QuicConnectionCallback triggered! 14
2022-09-14 17:03:38 [435930] INFO  ../nng/src/supplemental/quic/quic_api.c:394  QuicConnectionCallback: [conn][0x61f000000080] Resumption ticket received (1764 bytes):

2022-09-14 17:03:42 [435930] WARN  ../nng/src/mqtt/protocol/mqtt/mqtt_quic.c:552  mqtt_timer_cb: 5 0
2022-09-14 17:03:47 [435930] WARN  ../nng/src/mqtt/protocol/mqtt/mqtt_quic.c:552  mqtt_timer_cb: 5 1
2022-09-14 17:03:52 [435930] WARN  ../nng/src/mqtt/protocol/mqtt/mqtt_quic.c:552  mqtt_timer_cb: 5 2
2022-09-14 17:03:52 [435930] WARN  ../nng/src/mqtt/protocol/mqtt/mqtt_quic.c:556  mqtt_timer_cb: Close the quic connection due to timeout
2022-09-14 17:04:18 [435930] INFO  ../nng/src/supplemental/quic/quic_api.c:307  QuicConnectionCallback: QuicConnectionCallback triggered! 1
2022-09-14 17:04:18 [435930] ERROR ../nng/src/supplemental/quic/quic_api.c:339  QuicConnectionCallback: [conn][0x61f000000080] Successfully shut down on idle.

2022-09-14 17:04:18 [435930] INFO  ../nng/src/supplemental/quic/quic_api.c:280  QuicStreamCallback: [strm][0x618000010080] QUIC_STREAM_EVENT shutdown: All done 1102416563

2022-09-14 17:04:18 [435930] INFO  ../nng/src/supplemental/quic/quic_api.c:280  QuicStreamCallback: [strm][0x618000010080] QUIC_STREAM_EVENT shutdown: All done 859053200

2022-09-14 17:04:18 [435930] INFO  ../nng/src/supplemental/quic/quic_api.c:307  QuicConnectionCallback: QuicConnectionCallback triggered! 3
2022-09-14 17:04:18 [435930] INFO  ../nng/src/supplemental/quic/quic_api.c:361  QuicConnectionCallback: [conn][0x61f000000080] QUIC_CONNECTION_EVENT_SHUTDOWN_COMPLETE: All done


2022-09-14 17:04:18 [435930] WARN  ../nng/src/supplemental/quic/quic_api.c:373  QuicConnectionCallback: stream disconnected!
2022-09-14 17:04:18 [435930] WARN  ../nng/src/mqtt/protocol/mqtt/mqtt_quic.c:777  quic_mqtt_stream_fini:  QUIC Stream closed, pipe finit!
AddressSanitizer:DEADLYSIGNAL
=================================================================
==435930==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000030 (pc 0x55555565193a bp 0x7fffdcdd1a60 sp 0x7fffdcdd1830 T46)
==435930==The signal is caused by a READ memory access.
==435930==Hint: address points to the zero page.
    #0 0x555555651939 in nano_msg_notify_disconnect ../nng/src/sp/protocol/mqtt/mqtt_parser.c:1051
    #1 0x555555642a2b in quic_mqtt_stream_fini ../nng/src/mqtt/protocol/mqtt/mqtt_quic.c:800
    #2 0x5555559197a1 in QuicConnectionCallback ../nng/src/supplemental/quic/quic_api.c:376
    #3 0x7ffff724b353 in QuicConnIndicateEvent ../nng/extern/msquic/src/core/connection.c:737
    #4 0x7ffff724e1c2 in QuicConnOnShutdownComplete ../nng/extern/msquic/src/core/connection.c:1466
    #5 0x7ffff7267ec7 in QuicConnDrainOperations ../nng/extern/msquic/src/core/connection.c:7425
    #6 0x7ffff7233c08 in QuicWorkerProcessConnection ../nng/extern/msquic/src/core/worker.c:510
    #7 0x7ffff7234ca4 in QuicWorkerLoop ../nng/extern/msquic/src/core/worker.c:668
    #8 0x7ffff7235440 in QuicWorkerThread ../nng/extern/msquic/src/core/worker.c:733
    #9 0x7ffff719458f in start_thread nptl/pthread_create.c:463
    #10 0x7ffff70b4222 in __clone (/lib/x86_64-linux-gnu/libc.so.6+0x119222)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV ../nng/src/sp/protocol/mqtt/mqtt_parser.c:1051 in nano_msg_notify_disconnect
Thread T46 created by T0 here:
    #0 0x7ffff75b4805 in pthread_create (/lib/x86_64-linux-gnu/libasan.so.5+0x3a805)
    #1 0x7ffff72c417d in CxPlatThreadCreate ../nng/extern/msquic/src/platform/platform_posix.c:653
    #2 0x7ffff7231d96 in QuicWorkerInitialize ../nng/extern/msquic/src/core/worker.c:117
    #3 0x7ffff723573f in QuicWorkerPoolInitialize ../nng/extern/msquic/src/core/worker.c:792
    #4 0x7ffff72136e6 in MsQuicRegistrationOpen ../nng/extern/msquic/src/core/registration.c:162
    #5 0x55555591a0d9 in quic_open ../nng/src/supplemental/quic/quic_api.c:509
    #6 0x555555643c7e in nng_mqtt_quic_open_keepalive ../nng/src/mqtt/protocol/mqtt/mqtt_quic.c:1141
    #7 0x5555555d4500 in bridge_quic_client ../nanomq/bridge.c:251
    #8 0x5555555d4bbb in bridge_client ../nanomq/bridge.c:307
    #9 0x5555555fc5ae in broker ../nanomq/apps/broker.c:896
    #10 0x5555555ffcbf in broker_start ../nanomq/apps/broker.c:1495
    #11 0x5555555d24f0 in main ../nanomq/nanomq.c:142
    #12 0x7ffff6fc3cb1 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x28cb1)

==435930==ABORTING
[1] + Done                       "/usr/bin/gdb" --interpreter=mi --tty=${DbgTerm} 0<"/tmp/Microsoft-MIEngine-In-23gays5j.qfr" 1>"/tmp/Microsoft-MIEngine-Out-e1iynjsm.l2r"```

**Comment by JaylinYu** [comment]
Fixed in #287
