### ISSUE TITLE
Memleak caused by https://github.com/emqx/nanomq/issues/1045

### ISSUE THREAD

**Issue by JaylinYu** [nanomq/NanoNNG#437]
=================================================================
==197857==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 256 byte(s) in 1 object(s) allocated from:
    #0 0x7f7717651867 in __interceptor_malloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cpp:145
    #1 0x55f78e367f84 in nni_alloc /home/jaylin/Projects/EdgeComputing/nanomq/nng/src/platform/posix/posix_alloc.c:20
    #2 0x55f78e336fd4 in nng_alloc /home/jaylin/Projects/EdgeComputing/nanomq/nng/src/nng.c:60
    #3 0x55f78e38bad0 in conn_param_alloc /home/jaylin/Projects/EdgeComputing/nanomq/nng/src/sp/protocol/mqtt/mqtt_parser.c:853
    #4 0x55f78e6c2fdc in tcptran_pipe_nego_cb /home/jaylin/Projects/EdgeComputing/nanomq/nng/src/sp/transport/mqtt/broker_tcp.c:353
    #5 0x55f78e3623af in nni_taskq_thread /home/jaylin/Projects/EdgeComputing/nanomq/nng/src/core/taskq.c:50
    #6 0x55f78e363767 in nni_thr_wrap /home/jaylin/Projects/EdgeComputing/nanomq/nng/src/core/thread.c:94
    #7 0x55f78e36c91c in nni_plat_thr_main /home/jaylin/Projects/EdgeComputing/nanomq/nng/src/platform/posix/posix_thread.c:266
    #8 0x7f7716f29b42 in start_thread nptl/pthread_create.c:442

Indirect leak of 64 byte(s) in 1 object(s) allocated from:
    #0 0x7f7717651a37 in __interceptor_calloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cpp:154
    #1 0x55f78e367fb5 in nni_zalloc /home/jaylin/Projects/EdgeComputing/nanomq/nng/src/platform/posix/posix_alloc.c:26
    #2 0x55f78e3cc811 in property_alloc /home/jaylin/Projects/EdgeComputing/nanomq/nng/src/supplemental/mqtt/mqtt_codec.c:3327
    #3 0x55f78e3ceae7 in decode_buf_properties /home/jaylin/Projects/EdgeComputing/nanomq/nng/src/supplemental/mqtt/mqtt_codec.c:3753
    #4 0x55f78e389874 in conn_handler /home/jaylin/Projects/EdgeComputing/nanomq/nng/src/sp/protocol/mqtt/mqtt_parser.c:626
    #5 0x55f78e6c3086 in tcptran_pipe_nego_cb /home/jaylin/Projects/EdgeComputing/nanomq/nng/src/sp/transport/mqtt/broker_tcp.c:355
    #6 0x55f78e3623af in nni_taskq_thread /home/jaylin/Projects/EdgeComputing/nanomq/nng/src/core/taskq.c:50
    #7 0x55f78e363767 in nni_thr_wrap /home/jaylin/Projects/EdgeComputing/nanomq/nng/src/core/thread.c:94
    #8 0x55f78e36c91c in nni_plat_thr_main /home/jaylin/Projects/EdgeComputing/nanomq/nng/src/platform/posix/posix_thread.c:266
    #9 0x7f7716f29b42 in start_thread nptl/pthread_create.c:442

Indirect leak of 64 byte(s) in 1 object(s) allocated from:
    #0 0x7f7717651a37 in __interceptor_calloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cpp:154
    #1 0x55f78e367fb5 in nni_zalloc /home/jaylin/Projects/EdgeComputing/nanomq/nng/src/platform/posix/posix_alloc.c:26
    #2 0x55f78e3cc811 in property_alloc /home/jaylin/Projects/EdgeComputing/nanomq/nng/src/supplemental/mqtt/mqtt_codec.c:3327
    #3 0x55f78e3cd1e7 in property_parse /home/jaylin/Projects/EdgeComputing/nanomq/nng/src/supplemental/mqtt/mqtt_codec.c:3483
    #4 0x55f78e3cec72 in decode_buf_properties /home/jaylin/Projects/EdgeComputing/nanomq/nng/src/supplemental/mqtt/mqtt_codec.c:3763
    #5 0x55f78e389874 in conn_handler /home/jaylin/Projects/EdgeComputing/nanomq/nng/src/sp/protocol/mqtt/mqtt_parser.c:626
    #6 0x55f78e6c3086 in tcptran_pipe_nego_cb /home/jaylin/Projects/EdgeComputing/nanomq/nng/src/sp/transport/mqtt/broker_tcp.c:355
    #7 0x55f78e3623af in nni_taskq_thread /home/jaylin/Projects/EdgeComputing/nanomq/nng/src/core/taskq.c:50
    #8 0x55f78e363767 in nni_thr_wrap /home/jaylin/Projects/EdgeComputing/nanomq/nng/src/core/thread.c:94
    #9 0x55f78e36c91c in nni_plat_thr_main /home/jaylin/Projects/EdgeComputing/nanomq/nng/src/platform/posix/posix_thread.c:266
    #10 0x7f7716f29b42 in start_thread nptl/pthread_create.c:442

Indirect leak of 64 byte(s) in 1 object(s) allocated from:
    #0 0x7f7717651a37 in __interceptor_calloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cpp:154
    #1 0x55f78e367fb5 in nni_zalloc /home/jaylin/Projects/EdgeComputing/nanomq/nng/src/platform/posix/posix_alloc.c:26
    #2 0x55f78e3cc811 in property_alloc /home/jaylin/Projects/EdgeComputing/nanomq/nng/src/supplemental/mqtt/mqtt_codec.c:3327
    #3 0x55f78e3ccdc6 in property_set_value_str /home/jaylin/Projects/EdgeComputing/nanomq/nng/src/supplemental/mqtt/mqtt_codec.c:3444
    #4 0x55f78e389ee4 in conn_handler /home/jaylin/Projects/EdgeComputing/nanomq/nng/src/sp/protocol/mqtt/mqtt_parser.c:658
    #5 0x55f78e6c3086 in tcptran_pipe_nego_cb /home/jaylin/Projects/EdgeComputing/nanomq/nng/src/sp/transport/mqtt/broker_tcp.c:355
    #6 0x55f78e3623af in nni_taskq_thread /home/jaylin/Projects/EdgeComputing/nanomq/nng/src/core/taskq.c:50
    #7 0x55f78e363767 in nni_thr_wrap /home/jaylin/Projects/EdgeComputing/nanomq/nng/src/core/thread.c:94
    #8 0x55f78e36c91c in nni_plat_thr_main /home/jaylin/Projects/EdgeComputing/nanomq/nng/src/platform/posix/posix_thread.c:266
    #9 0x7f7716f29b42 in start_thread nptl/pthread_create.c:442

Indirect leak of 16 byte(s) in 1 object(s) allocated from:
    #0 0x7f7717651867 in __interceptor_malloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cpp:145
    #1 0x55f78e367f84 in nni_alloc /home/jaylin/Projects/EdgeComputing/nanomq/nng/src/platform/posix/posix_alloc.c:20
    #2 0x55f78e361b95 in nni_strdup /home/jaylin/Projects/EdgeComputing/nanomq/nng/src/core/strs.c:34
    #3 0x55f78e3370dc in nng_strdup /home/jaylin/Projects/EdgeComputing/nanomq/nng/src/nng.c:102
    #4 0x55f78e389ba2 in conn_handler /home/jaylin/Projects/EdgeComputing/nanomq/nng/src/sp/protocol/mqtt/mqtt_parser.c:647
    #5 0x55f78e6c3086 in tcptran_pipe_nego_cb /home/jaylin/Projects/EdgeComputing/nanomq/nng/src/sp/transport/mqtt/broker_tcp.c:355
    #6 0x55f78e3623af in nni_taskq_thread /home/jaylin/Projects/EdgeComputing/nanomq/nng/src/core/taskq.c:50
    #7 0x55f78e363767 in nni_thr_wrap /home/jaylin/Projects/EdgeComputing/nanomq/nng/src/core/thread.c:94
    #8 0x55f78e36c91c in nni_plat_thr_main /home/jaylin/Projects/EdgeComputing/nanomq/nng/src/platform/posix/posix_thread.c:266
    #9 0x7f7716f29b42 in start_thread nptl/pthread_create.c:442

Indirect leak of 5 byte(s) in 1 object(s) allocated from:
    #0 0x7f7717651867 in __interceptor_malloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cpp:145
    #1 0x55f78e367f84 in nni_alloc /home/jaylin/Projects/EdgeComputing/nanomq/nng/src/platform/posix/posix_alloc.c:20
    #2 0x55f78e336fd4 in nng_alloc /home/jaylin/Projects/EdgeComputing/nanomq/nng/src/nng.c:60
    #3 0x55f78e3870d3 in copyn_utf8_str /home/jaylin/Projects/EdgeComputing/nanomq/nng/src/sp/protocol/mqtt/mqtt_parser.c:238
    #4 0x55f78e388ff3 in conn_handler /home/jaylin/Projects/EdgeComputing/nanomq/nng/src/sp/protocol/mqtt/mqtt_parser.c:597
    #5 0x55f78e6c3086 in tcptran_pipe_nego_cb /home/jaylin/Projects/EdgeComputing/nanomq/nng/src/sp/transport/mqtt/broker_tcp.c:355
    #6 0x55f78e3623af in nni_taskq_thread /home/jaylin/Projects/EdgeComputing/nanomq/nng/src/core/taskq.c:50
    #7 0x55f78e363767 in nni_thr_wrap /home/jaylin/Projects/EdgeComputing/nanomq/nng/src/core/thread.c:94
    #8 0x55f78e36c91c in nni_plat_thr_main /home/jaylin/Projects/EdgeComputing/nanomq/nng/src/platform/posix/posix_thread.c:266
    #9 0x7f7716f29b42 in start_thread nptl/pthread_create.c:442

SUMMARY: AddressSanitizer: 469 byte(s) leaked in 6 allocation(s).

**Comment by JaylinYu** [comment]
=================================================================
==198501==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 64 byte(s) in 1 object(s) allocated from:
    #0 0x7f0748fb3a37 in __interceptor_calloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cpp:154
    #1 0x55d007099fb5 in nni_zalloc /home/jaylin/Projects/EdgeComputing/nanomq/nng/src/platform/posix/posix_alloc.c:26
    #2 0x55d0070fe811 in property_alloc /home/jaylin/Projects/EdgeComputing/nanomq/nng/src/supplemental/mqtt/mqtt_codec.c:3327
    #3 0x55d007100ae7 in decode_buf_properties /home/jaylin/Projects/EdgeComputing/nanomq/nng/src/supplemental/mqtt/mqtt_codec.c:3753
    #4 0x55d007100e91 in decode_properties /home/jaylin/Projects/EdgeComputing/nanomq/nng/src/supplemental/mqtt/mqtt_codec.c:3779
    #5 0x55d007102253 in nni_mqtt_pubres_decode /home/jaylin/Projects/EdgeComputing/nanomq/nng/src/supplemental/mqtt/mqtt_codec.c:4032
    #6 0x55d0073f7b7b in tcptran_pipe_recv_cb /home/jaylin/Projects/EdgeComputing/nanomq/nng/src/sp/transport/mqtt/broker_tcp.c:745
    #7 0x55d0070943af in nni_taskq_thread /home/jaylin/Projects/EdgeComputing/nanomq/nng/src/core/taskq.c:50
    #8 0x55d007095767 in nni_thr_wrap /home/jaylin/Projects/EdgeComputing/nanomq/nng/src/core/thread.c:94
    #9 0x55d00709e91c in nni_plat_thr_main /home/jaylin/Projects/EdgeComputing/nanomq/nng/src/platform/posix/posix_thread.c:266
    #10 0x7f074888bb42 in start_thread nptl/pthread_create.c:442

Indirect leak of 64 byte(s) in 1 object(s) allocated from:
    #0 0x7f0748fb3a37 in __interceptor_calloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cpp:154
    #1 0x55d007099fb5 in nni_zalloc /home/jaylin/Projects/EdgeComputing/nanomq/nng/src/platform/posix/posix_alloc.c:26
    #2 0x55d0070fe811 in property_alloc /home/jaylin/Projects/EdgeComputing/nanomq/nng/src/supplemental/mqtt/mqtt_codec.c:3327
    #3 0x55d0070ff1e7 in property_parse /home/jaylin/Projects/EdgeComputing/nanomq/nng/src/supplemental/mqtt/mqtt_codec.c:3483
    #4 0x55d007100c72 in decode_buf_properties /home/jaylin/Projects/EdgeComputing/nanomq/nng/src/supplemental/mqtt/mqtt_codec.c:3763
    #5 0x55d007100e91 in decode_properties /home/jaylin/Projects/EdgeComputing/nanomq/nng/src/supplemental/mqtt/mqtt_codec.c:3779
    #6 0x55d007102253 in nni_mqtt_pubres_decode /home/jaylin/Projects/EdgeComputing/nanomq/nng/src/supplemental/mqtt/mqtt_codec.c:4032
    #7 0x55d0073f7b7b in tcptran_pipe_recv_cb /home/jaylin/Projects/EdgeComputing/nanomq/nng/src/sp/transport/mqtt/broker_tcp.c:745
    #8 0x55d0070943af in nni_taskq_thread /home/jaylin/Projects/EdgeComputing/nanomq/nng/src/core/taskq.c:50
    #9 0x55d007095767 in nni_thr_wrap /home/jaylin/Projects/EdgeComputing/nanomq/nng/src/core/thread.c:94
    #10 0x55d00709e91c in nni_plat_thr_main /home/jaylin/Projects/EdgeComputing/nanomq/nng/src/platform/posix/posix_thread.c:266
    #11 0x7f074888bb42 in start_thread nptl/pthread_create.c:442

SUMMARY: AddressSanitizer: 128 byte(s) leaked in 2 allocation(s).

target-1675834211.862917.txt
