### ISSUE TITLE
Failed stream close of QUIC 

### ISSUE THREAD

**Issue by JaylinYu** [nanomq/NanoNNG#801]
``Test quic send message:
AddressSanitizer:DEADLYSIGNAL
=================================================================
==1183514==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000018 (pc 0x555d5f62787a bp 0x7ffd955b6150 sp 0x7ffd955b6130 T0)
==1183514==The signal is caused by a READ memory access.
==1183514==Hint: address points to the zero page.
    #0 0x555d5f62787a in nng_stream_send /home/jaylin/Projects/nanomq/nng/src/core/stream.c:263:5
    #1 0x555d5f6619b4 in stream_xfr_start /home/jaylin/Projects/nanomq/nng/src/testing/streams.c:49:2
    #2 0x555d5f661a77 in nuts_stream_send_start /home/jaylin/Projects/nanomq/nng/src/testing/streams.c:144:2
    #3 0x555d5f5e6335 in test_quic_send_message /home/jaylin/Projects/nanomq/nng/src/supplemental/quic/quic_api_test.c:56:6
    #4 0x555d5f5e8e26 in test_do_run_ /home/jaylin/Projects/nanomq/nng/src/testing/acutest.h:1026:9
    #5 0x555d5f5e54c9 in test_run_ /home/jaylin/Projects/nanomq/nng/src/testing/acutest.h:1122:23
    #6 0x555d5f5e2b59 in main /home/jaylin/Projects/nanomq/nng/src/testing/acutest.h:1724:13
    #7 0x7faf98a29d8f in __libc_start_call_main csu/../sysdeps/nptl/libc_start_call_main.h:58:16
    #8 0x7faf98a29e3f in __libc_start_main csu/../csu/libc-start.c:392:3
    #9 0x555d5f523704 in _start (/home/jaylin/Projects/nanomq/nng/build/src/supplemental/quic/quic_api_test+0x82704) (BuildId: 341cb2b5e180c52bf9ee1244052ca8614adb40bb)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV /home/jaylin/Projects/nanomq/nng/src/core/stream.c:263:5 in nng_stream_send
==1183514==ABORTING
Test quic recv message:
AddressSanitizer:DEADLYSIGNAL
=================================================================
==1183578==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000018 (pc 0x555d5f62787a bp 0x7ffd955b60d0 sp 0x7ffd955b60b0 T0)
==1183578==The signal is caused by a READ memory access.
==1183578==Hint: address points to the zero page.
    #0 0x555d5f62787a in nng_stream_send /home/jaylin/Projects/nanomq/nng/src/core/stream.c:263:5
    #1 0x555d5f6619b4 in stream_xfr_start /home/jaylin/Projects/nanomq/nng/src/testing/streams.c:49:2
    #2 0x555d5f661a77 in nuts_stream_send_start /home/jaylin/Projects/nanomq/nng/src/testing/streams.c:144:2
    #3 0x555d5f5e688c in test_quic_recv_message /home/jaylin/Projects/nanomq/nng/src/supplemental/quic/quic_api_test.c:100:6
    #4 0x555d5f5e8e26 in test_do_run_ /home/jaylin/Projects/nanomq/nng/src/testing/acutest.h:1026:9
    #5 0x555d5f5e54c9 in test_run_ /home/jaylin/Projects/nanomq/nng/src/testing/acutest.h:1122:23
    #6 0x555d5f5e2b59 in main /home/jaylin/Projects/nanomq/nng/src/testing/acutest.h:1724:13
    #7 0x7faf98a29d8f in __libc_start_call_main csu/../sysdeps/nptl/libc_start_call_main.h:58:16
    #8 0x7faf98a29e3f in __libc_start_main csu/../csu/libc-start.c:392:3
    #9 0x555d5f523704 in _start (/home/jaylin/Projects/nanomq/nng/build/src/supplemental/quic/quic_api_test+0x82704) (BuildId: 341cb2b5e180c52bf9ee1244052ca8614adb40bb)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV /home/jaylin/Projects/nanomq/nng/src/core/stream.c:263:5 in nng_stream_send
==1183578==ABORTING
Test quic mqtt connection:
AddressSanitizer:DEADLYSIGNAL
=================================================================
==1183642==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000018 (pc 0x555d5f62787a bp 0x7ffd955b60d0 sp 0x7ffd955b60b0 T0)
==1183642==The signal is caused by a READ memory access.
==1183642==Hint: address points to the zero page.
    #0 0x555d5f62787a in nng_stream_send /home/jaylin/Projects/nanomq/nng/src/core/stream.c:263:5
    #1 0x555d5f6619b4 in stream_xfr_start /home/jaylin/Projects/nanomq/nng/src/testing/streams.c:49:2
    #2 0x555d5f661a77 in nuts_stream_send_start /home/jaylin/Projects/nanomq/nng/src/testing/streams.c:144:2
    #3 0x555d5f5e6ebc in test_quic_mqtt_connection /home/jaylin/Projects/nanomq/nng/src/supplemental/quic/quic_api_test.c:147:6
    #4 0x555d5f5e8e26 in test_do_run_ /home/jaylin/Projects/nanomq/nng/src/testing/acutest.h:1026:9
    #5 0x555d5f5e54c9 in test_run_ /home/jaylin/Projects/nanomq/nng/src/testing/acutest.h:1122:23
    #6 0x555d5f5e2b59 in main /home/jaylin/Projects/nanomq/nng/src/testing/acutest.h:1724:13
    #7 0x7faf98a29d8f in __libc_start_call_main csu/../sysdeps/nptl/libc_start_call_main.h:58:16
    #8 0x7faf98a29e3f in __libc_start_main csu/../csu/libc-start.c:392:3
    #9 0x555d5f523704 in _start (/home/jaylin/Projects/nanomq/nng/build/src/supplemental/quic/quic_api_test+0x82704) (BuildId: 341cb2b5e180c52bf9ee1244052ca8614adb40bb)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV /home/jaylin/Projects/nanomq/nng/src/core/stream.c:263:5 in nng_stream_send
==1183642==ABORTING
Test quic multi-stream:
AddressSanitizer:DEADLYSIGNAL
=================================================================
==1183706==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000008 (pc 0x555d5f6277d6 bp 0x7ffd955b6270 sp 0x7ffd955b6260 T0)
==1183706==The signal is caused by a READ memory access.
==1183706==Hint: address points to the zero page.
    #0 0x555d5f6277d6 in nng_stream_close /home/jaylin/Projects/nanomq/nng/src/core/stream.c:249:5
    #1 0x555d5f5e75cb in test_quic_multi_stream /home/jaylin/Projects/nanomq/nng/src/supplemental/quic/quic_api_test.c:181:2
    #2 0x555d5f5e8e26 in test_do_run_ /home/jaylin/Projects/nanomq/nng/src/testing/acutest.h:1026:9
    #3 0x555d5f5e54c9 in test_run_ /home/jaylin/Projects/nanomq/nng/src/testing/acutest.h:1122:23
    #4 0x555d5f5e2b59 in main /home/jaylin/Projects/nanomq/nng/src/testing/acutest.h:1724:13
    #5 0x7faf98a29d8f in __libc_start_call_main csu/../sysdeps/nptl/libc_start_call_main.h:58:16
    #6 0x7faf98a29e3f in __libc_start_main csu/../csu/libc-start.c:392:3
    #7 0x555d5f523704 in _start (/home/jaylin/Projects/nanomq/nng/build/src/supplemental/quic/quic_api_test+0x82704) (BuildId: 341cb2b5e180c52bf9ee1244052ca8614adb40bb)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV /home/jaylin/Projects/nanomq/nng/src/core/stream.c:249:5 in nng_stream_close
==1183706==ABORTING
Summary:
  Count of all unit tests:        5
  Count of run unit tests:        5
  Count of failed unit tests:     5
  Count of skipped unit tests:    0
FAILED: 5 of 5 unit tests have failed.
``

Above is a failed CI run on my env.

**Comment by wanghaEMQ** [comment]
The error was more likely to happen in aio or quic dialer start.
