### ISSUE TITLE
qos_first feature of QUIC bridging has a potential memleak issue when stream/connection reconnects

### ISSUE THREAD

**Issue by JaylinYu** [nanomq/NanoNNG#873]
**Describe the bug**

**Expected behavior**

**Actual Behavior**
Describe what occurred.

**To Reproduce**
If possible include actual reproduction test code here.
Minimal C test cases are perferred.

** Environment Details **
 - NanoMQ version
 - Operating system and version
 - Compiler and language used
 - testing scenario

**Client SDK**
If possible include the mqtt sdk you used to connect to nanomq
Minimal C test cases are perferred.

**Additional context**

**Comment by JaylinYu** [comment]
==2490841==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 768096 byte(s) in 4572 object(s) allocated from:
    #0 0x7f7b056b4a57 in __interceptor_calloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cpp:154
    #1 0x561707861ad5 in nni_zalloc /home/jaylin/Projects/nanomq/nng/src/platform/posix/posix_alloc.c:26
    #2 0x56170784b712 in nni_msg_alloc /home/jaylin/Projects/nanomq/nng/src/core/message.c:387
    #3 0x5617078bcfa3 in nni_mqtt_msg_alloc /home/jaylin/Projects/nanomq/nng/src/supplemental/mqtt/mqtt_msg.c:60
    #4 0x5617078a3ec3 in nng_mqtt_msg_alloc /home/jaylin/Projects/nanomq/nng/src/supplemental/mqtt/mqtt_public.c:20
    #5 0x5617077dddf8 in bridge_publish_msg /home/jaylin/Projects/nanomq/nanomq/bridge.c:239
    #6 0x561707823069 in bridge_handler /home/jaylin/Projects/nanomq/nanomq/apps/broker.c:236
    #7 0x561707826807 in server_cb /home/jaylin/Projects/nanomq/nanomq/apps/broker.c:574
    #8 0x56170785c788 in nni_taskq_thread /home/jaylin/Projects/nanomq/nng/src/core/taskq.c:50
    #9 0x56170785daa9 in nni_thr_wrap /home/jaylin/Projects/nanomq/nng/src/core/thread.c:94
    #10 0x561707866430 in nni_plat_thr_main /home/jaylin/Projects/nanomq/nng/src/platform/posix/posix_thread.c:266
    #11 0x7f7b04e94ac2 in start_thread nptl/pthread_create.c:442

Indirect leak of 1385316 byte(s) in 4572 object(s) allocated from:
    #0 0x7f7b056b4a57 in __interceptor_calloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cpp:154
    #1 0x561707861ad5 in nni_zalloc /home/jaylin/Projects/nanomq/nng/src/platform/posix/posix_alloc.c:26
    #2 0x56170784a303 in nni_chunk_grow /home/jaylin/Projects/nanomq/nng/src/core/message.c:140
    #3 0x56170784abc6 in nni_chunk_append /home/jaylin/Projects/nanomq/nng/src/core/message.c:244
    #4 0x56170784bee7 in nni_msg_append /home/jaylin/Projects/nanomq/nng/src/core/message.c:525
    #5 0x5617078ac74d in nni_mqttv5_msg_encode_publish /home/jaylin/Projects/nanomq/nng/src/supplemental/mqtt/mqtt_codec.c:1282
    #6 0x5617078a6b61 in nni_mqttv5_msg_encode /home/jaylin/Projects/nanomq/nng/src/supplemental/mqtt/mqtt_codec.c:195
    #7 0x5617078a3f1d in nng_mqttv5_msg_encode /home/jaylin/Projects/nanomq/nng/src/supplemental/mqtt/mqtt_public.c:38
    #8 0x5617078230c8 in bridge_handler /home/jaylin/Projects/nanomq/nanomq/apps/broker.c:246
    #9 0x561707826807 in server_cb /home/jaylin/Projects/nanomq/nanomq/apps/broker.c:574
    #10 0x56170785c788 in nni_taskq_thread /home/jaylin/Projects/nanomq/nng/src/core/taskq.c:50
    #11 0x56170785daa9 in nni_thr_wrap /home/jaylin/Projects/nanomq/nng/src/core/thread.c:94
    #12 0x561707866430 in nni_plat_thr_main /home/jaylin/Projects/nanomq/nng/src/platform/posix/posix_thread.c:266
    #13 0x7f7b04e94ac2 in start_thread nptl/pthread_create.c:442

Indirect leak of 1170432 byte(s) in 4572 object(s) allocated from:
    #0 0x7f7b056b4887 in __interceptor_malloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cpp:145
    #1 0x561707861aa4 in nni_alloc /home/jaylin/Projects/nanomq/nng/src/platform/posix/posix_alloc.c:20
    #2 0x5617078b604b in mqtt_buf_create /home/jaylin/Projects/nanomq/nng/src/supplemental/mqtt/mqtt_codec.c:3087
    #3 0x5617078bdc8e in nni_mqtt_msg_set_publish_payload /home/jaylin/Projects/nanomq/nng/src/supplemental/mqtt/mqtt_msg.c:246
    #4 0x5617078a46b6 in nng_mqtt_msg_set_publish_payload /home/jaylin/Projects/nanomq/nng/src/supplemental/mqtt/mqtt_public.c:359
    #5 0x5617077ddf09 in bridge_publish_msg /home/jaylin/Projects/nanomq/nanomq/bridge.c:245
    #6 0x561707823069 in bridge_handler /home/jaylin/Projects/nanomq/nanomq/apps/broker.c:236
    #7 0x561707826807 in server_cb /home/jaylin/Projects/nanomq/nanomq/apps/broker.c:574
    #8 0x56170785c788 in nni_taskq_thread /home/jaylin/Projects/nanomq/nng/src/core/taskq.c:50
    #9 0x56170785daa9 in nni_thr_wrap /home/jaylin/Projects/nanomq/nng/src/core/thread.c:94
    #10 0x561707866430 in nni_plat_thr_main /home/jaylin/Projects/nanomq/nng/src/platform/posix/posix_thread.c:266
    #11 0x7f7b04e94ac2 in start_thread nptl/pthread_create.c:442

Indirect leak of 658368 byte(s) in 4572 object(s) allocated from:
    #0 0x7f7b056b4a57 in __interceptor_calloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cpp:154
    #1 0x561707861ad5 in nni_zalloc /home/jaylin/Projects/nanomq/nng/src/platform/posix/posix_alloc.c:26
    #2 0x5617078bcec5 in nni_mqtt_msg_proto_data_alloc /home/jaylin/Projects/nanomq/nng/src/supplemental/mqtt/mqtt_msg.c:38
    #3 0x5617078bcfe1 in nni_mqtt_msg_alloc /home/jaylin/Projects/nanomq/nng/src/supplemental/mqtt/mqtt_msg.c:64
    #4 0x5617078a3ec3 in nng_mqtt_msg_alloc /home/jaylin/Projects/nanomq/nng/src/supplemental/mqtt/mqtt_public.c:20
    #5 0x5617077dddf8 in bridge_publish_msg /home/jaylin/Projects/nanomq/nanomq/bridge.c:239
    #6 0x561707823069 in bridge_handler /home/jaylin/Projects/nanomq/nanomq/apps/broker.c:236
    #7 0x561707826807 in server_cb /home/jaylin/Projects/nanomq/nanomq/apps/broker.c:574
    #8 0x56170785c788 in nni_taskq_thread /home/jaylin/Projects/nanomq/nng/src/core/taskq.c:50
    #9 0x56170785daa9 in nni_thr_wrap /home/jaylin/Projects/nanomq/nng/src/core/thread.c:94
    #10 0x561707866430 in nni_plat_thr_main /home/jaylin/Projects/nanomq/nng/src/platform/posix/posix_thread.c:266
    #11 0x7f7b04e94ac2 in start_thread nptl/pthread_create.c:442

Indirect leak of 45720 byte(s) in 4572 object(s) allocated from:
    #0 0x7f7b056b4887 in __interceptor_malloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cpp:145
    #1 0x561707861aa4 in nni_alloc /home/jaylin/Projects/nanomq/nng/src/platform/posix/posix_alloc.c:20
    #2 0x5617078b604b in mqtt_buf_create /home/jaylin/Projects/nanomq/nng/src/supplemental/mqtt/mqtt_codec.c:3087
    #3 0x5617078bda81 in nni_mqtt_msg_set_publish_topic /home/jaylin/Projects/nanomq/nng/src/supplemental/mqtt/mqtt_msg.c:218
    #4 0x5617078a45ef in nng_mqtt_msg_set_publish_topic /home/jaylin/Projects/nanomq/nng/src/supplemental/mqtt/mqtt_public.c:329
    #5 0x5617077ddf40 in bridge_publish_msg /home/jaylin/Projects/nanomq/nanomq/bridge.c:246
    #6 0x561707823069 in bridge_handler /home/jaylin/Projects/nanomq/nanomq/apps/broker.c:236
    #7 0x561707826807 in server_cb /home/jaylin/Projects/nanomq/nanomq/apps/broker.c:574
    #8 0x56170785c788 in nni_taskq_thread /home/jaylin/Projects/nanomq/nng/src/core/taskq.c:50
    #9 0x56170785daa9 in nni_thr_wrap /home/jaylin/Projects/nanomq/nng/src/core/thread.c:94
    #10 0x561707866430 in nni_plat_thr_main /home/jaylin/Projects/nanomq/nng/src/platform/posix/posix_thread.c:266
    #11 0x7f7b04e94ac2 in start_thread nptl/pthread_create.c:442

SUMMARY: AddressSanitizer: 4027932 byte(s) leaked in 22860 allocation(s).
