### ISSUE TITLE
Weird stack use after return

### ISSUE THREAD

**Issue by wanghaEMQ** [nanomq/NanoNNG#889]
**Describe the bug**
```
=================================================================
==4171344==ERROR: AddressSanitizer: stack-use-after-return on address 0x7f02d9565230 at pc 0x7f02e48644cc bp 0x7f02decf3340 sp 0x7f02decf2b00
READ of size 2 at 0x7f02d9565230 thread T2
    #0 0x7f02e48644cb  (/lib64/libasan.so.8+0x644cb) (BuildId: 542ad02088f38edfdba9d4bfa465b2299f512d3e)
    #1 0x7f02e48ba3d6  (/lib64/libasan.so.8+0xba3d6) (BuildId: 542ad02088f38edfdba9d4bfa465b2299f512d3e)
    #2 0x7f02e48bbda3 in sendmsg (/lib64/libasan.so.8+0xbbda3) (BuildId: 542ad02088f38edfdba9d4bfa465b2299f512d3e)
    #3 0x8d9758 in tcp_dowrite /home/wangha/Documents/NanoMQ_mirror/nng/src/platform/posix/posix_tcpconn.c:69
    #4 0x8da3f6 in tcp_cb /home/wangha/Documents/NanoMQ_mirror/nng/src/platform/posix/posix_tcpconn.c:245
    #5 0x73e30a in nni_posix_poll_thr /home/wangha/Documents/NanoMQ_mirror/nng/src/platform/posix/posix_pollq_epoll.c:291
    #6 0x73495b in nni_thr_wrap /home/wangha/Documents/NanoMQ_mirror/nng/src/core/thread.c:94
    #7 0x73c988 in nni_plat_thr_main /home/wangha/Documents/NanoMQ_mirror/nng/src/platform/posix/posix_thread.c:266
    #8 0x7f02e38ae946 in start_thread (/lib64/libc.so.6+0x8c946) (BuildId: f888be5f5e7d58e04cabb8c675c7ab94e77dd68c)
    #9 0x7f02e393485f in __clone3 (/lib64/libc.so.6+0x11285f) (BuildId: f888be5f5e7d58e04cabb8c675c7ab94e77dd68c)

Address 0x7f02d9565230 is located in stack of thread T4 at offset 48 in frame
    #0 0x78c5ef in decode_buf_properties /home/wangha/Documents/NanoMQ_mirror/nng/src/supplemental/mqtt/mqtt_codec.c:3880

  This frame has 4 object(s):
    [48, 49) 'bytes' (line 3885) <== Memory access at offset 48 partially overflows this variable
    [64, 65) 'prop_id' (line 3912)
    [80, 84) 'prop_len' (line 3884)
    [96, 112) 'buf' (line 3902)
HINT: this may be a false positive if your program uses some custom stack unwind mechanism, swapcontext or vfork
      (longjmp and C++ exceptions *are* supported)
Thread T4 created by T0 here:
    #0 0x7f02e4848956 in pthread_create (/lib64/libasan.so.8+0x48956) (BuildId: 542ad02088f38edfdba9d4bfa465b2299f512d3e)
    #1 0x73ca81 in nni_plat_thr_init /home/wangha/Documents/NanoMQ_mirror/nng/src/platform/posix/posix_thread.c:279
    #2 0x734bfe in nni_thr_init /home/wangha/Documents/NanoMQ_mirror/nng/src/core/thread.c:121
    #3 0x7339da in nni_taskq_init /home/wangha/Documents/NanoMQ_mirror/nng/src/core/taskq.c:95
    #4 0x734667 in nni_taskq_sys_init /home/wangha/Documents/NanoMQ_mirror/nng/src/core/taskq.c:287
    #5 0x71ec80 in nni_init_helper /home/wangha/Documents/NanoMQ_mirror/nng/src/core/init.c:35
    #6 0x73cd88 in nni_plat_init /home/wangha/Documents/NanoMQ_mirror/nng/src/platform/posix/posix_thread.c:422
    #7 0x71ecea in nni_init /home/wangha/Documents/NanoMQ_mirror/nng/src/core/init.c:57
    #8 0x77614b in nng_mtx_alloc /home/wangha/Documents/NanoMQ_mirror/nng/src/supplemental/util/platform.c:93
    #9 0x7ceaa7 in conf_bridge_parse_ver2 /home/wangha/Documents/NanoMQ_mirror/nng/src/supplemental/nanolib/conf_ver2.c:1200
    #10 0x7d2e56 in conf_parse_ver2 /home/wangha/Documents/NanoMQ_mirror/nng/src/supplemental/nanolib/conf_ver2.c:1728
    #11 0x704ce6 in broker_start /home/wangha/Documents/NanoMQ_mirror/nanomq/apps/broker.c:1704
    #12 0x6f9a20 in main /home/wangha/Documents/NanoMQ_mirror/nanomq/nanomq.c:142
    #13 0x7f02e3849b89 in __libc_start_call_main (/lib64/libc.so.6+0x27b89) (BuildId: f888be5f5e7d58e04cabb8c675c7ab94e77dd68c)
    #14 0x7f02e3849c4a in __libc_start_main_alias_2 (/lib64/libc.so.6+0x27c4a) (BuildId: f888be5f5e7d58e04cabb8c675c7ab94e77dd68c)
    #15 0x6b4834 in _start (/home/wangha/Documents/NanoMQ_mirror/build/nanomq/nanomq+0x6b4834) (BuildId: 77511f25a38a3423bca6b0b22738f6af8f20813d)

SUMMARY: AddressSanitizer: stack-use-after-return (/lib64/libasan.so.8+0x644cb) (BuildId: 542ad02088f38edfdba9d4bfa465b2299f512d3e)
Shadow bytes around the buggy address:
  0x7f02d9564f80: f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 00 00 00 00
  0x7f02d9565000: f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 00 00 00 00
  0x7f02d9565080: f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 00 00 00 00
  0x7f02d9565100: f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5
  0x7f02d9565180: f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 00 00 00 00
=>0x7f02d9565200: f5 f5 f5 f5 f5 f5[f5]f5 f5 f5 f5 f5 f5 f5 f5 f5
  0x7f02d9565280: f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 00 00 00 00
  0x7f02d9565300: f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 00 00 00 00
  0x7f02d9565380: f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5
  0x7f02d9565400: f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5
  0x7f02d9565480: f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 00 00 00 00
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
Thread T2 created by T0 here:
    #0 0x7f02e4848956 in pthread_create (/lib64/libasan.so.8+0x48956) (BuildId: 542ad02088f38edfdba9d4bfa465b2299f512d3e)
    #1 0x73ca81 in nni_plat_thr_init /home/wangha/Documents/NanoMQ_mirror/nng/src/platform/posix/posix_thread.c:279
    #2 0x734bfe in nni_thr_init /home/wangha/Documents/NanoMQ_mirror/nng/src/core/thread.c:121
    #3 0x73eb0a in nni_posix_pollq_create /home/wangha/Documents/NanoMQ_mirror/nng/src/platform/posix/posix_pollq_epoll.c:386
    #4 0x73ebec in nni_posix_pollq_sysinit /home/wangha/Documents/NanoMQ_mirror/nng/src/platform/posix/posix_pollq_epoll.c:400
    #5 0x73ccb8 in nni_plat_init /home/wangha/Documents/NanoMQ_mirror/nng/src/platform/posix/posix_thread.c:396
    #6 0x71ecea in nni_init /home/wangha/Documents/NanoMQ_mirror/nng/src/core/init.c:57
    #7 0x77614b in nng_mtx_alloc /home/wangha/Documents/NanoMQ_mirror/nng/src/supplemental/util/platform.c:93
    #8 0x7ceaa7 in conf_bridge_parse_ver2 /home/wangha/Documents/NanoMQ_mirror/nng/src/supplemental/nanolib/conf_ver2.c:1200
    #9 0x7d2e56 in conf_parse_ver2 /home/wangha/Documents/NanoMQ_mirror/nng/src/supplemental/nanolib/conf_ver2.c:1728
    #10 0x704ce6 in broker_start /home/wangha/Documents/NanoMQ_mirror/nanomq/apps/broker.c:1704
    #11 0x6f9a20 in main /home/wangha/Documents/NanoMQ_mirror/nanomq/nanomq.c:142
    #12 0x7f02e3849b89 in __libc_start_call_main (/lib64/libc.so.6+0x27b89) (BuildId: f888be5f5e7d58e04cabb8c675c7ab94e77dd68c)
    #13 0x7f02e3849c4a in __libc_start_main_alias_2 (/lib64/libc.so.6+0x27c4a) (BuildId: f888be5f5e7d58e04cabb8c675c7ab94e77dd68c)
    #14 0x6b4834 in _start (/home/wangha/Documents/NanoMQ_mirror/build/nanomq/nanomq+0x6b4834) (BuildId: 77511f25a38a3423bca6b0b22738f6af8f20813d)

==4171344==ABORTING
```

**Comment by wanghaEMQ** [comment]
Second time.

```
==51312==ERROR: AddressSanitizer: stack-use-after-return on address 0x7f741954e030 at pc 0x7f7423e644cc bp 0x7f741e4f3340 sp 0x7f741e4f2b00
READ of size 2 at 0x7f741954e030 thread T2
    #0 0x7f7423e644cb  (/lib64/libasan.so.8+0x644cb) (BuildId: 542ad02088f38edfdba9d4bfa465b2299f512d3e)
    #1 0x7f7423eba3d6  (/lib64/libasan.so.8+0xba3d6) (BuildId: 542ad02088f38edfdba9d4bfa465b2299f512d3e)
    #2 0x7f7423ebbda3 in sendmsg (/lib64/libasan.so.8+0xbbda3) (BuildId: 542ad02088f38edfdba9d4bfa465b2299f512d3e)
    #3 0x8d974f in tcp_dowrite /home/wangha/Documents/NanoMQ_mirror/nng/src/platform/posix/posix_tcpconn.c:69
    #4 0x8da3ed in tcp_cb /home/wangha/Documents/NanoMQ_mirror/nng/src/platform/posix/posix_tcpconn.c:245
    #5 0x73e30a in nni_posix_poll_thr /home/wangha/Documents/NanoMQ_mirror/nng/src/platform/posix/posix_pollq_epoll.c:291
    #6 0x73495b in nni_thr_wrap /home/wangha/Documents/NanoMQ_mirror/nng/src/core/thread.c:94
    #7 0x73c988 in nni_plat_thr_main /home/wangha/Documents/NanoMQ_mirror/nng/src/platform/posix/posix_thread.c:266
    #8 0x7f7422eae946 in start_thread (/lib64/libc.so.6+0x8c946) (BuildId: f888be5f5e7d58e04cabb8c675c7ab94e77dd68c)
    #9 0x7f7422f3485f in __clone3 (/lib64/libc.so.6+0x11285f) (BuildId: f888be5f5e7d58e04cabb8c675c7ab94e77dd68c)

Address 0x7f741954e030 is located in stack of thread T4 at offset 48 in frame
    #0 0x8b90d7 in mqtt_pipe_timer_cb /home/wangha/Documents/NanoMQ_mirror/nng/src/mqtt/transport/tcp/mqtt_tcp.c:149

  This frame has 2 object(s):
    [48, 50) 'buf' (line 151) <== Memory access at offset 48 is inside this variable
    [64, 80) 'iov' (line 171)
HINT: this may be a false positive if your program uses some custom stack unwind mechanism, swapcontext or vfork
      (longjmp and C++ exceptions *are* supported)
Thread T4 created by T0 here:
    #0 0x7f7423e48956 in pthread_create (/lib64/libasan.so.8+0x48956) (BuildId: 542ad02088f38edfdba9d4bfa465b2299f512d3e)
    #1 0x73ca81 in nni_plat_thr_init /home/wangha/Documents/NanoMQ_mirror/nng/src/platform/posix/posix_thread.c:279
    #2 0x734bfe in nni_thr_init /home/wangha/Documents/NanoMQ_mirror/nng/src/core/thread.c:121
    #3 0x7339da in nni_taskq_init /home/wangha/Documents/NanoMQ_mirror/nng/src/core/taskq.c:95
    #4 0x734667 in nni_taskq_sys_init /home/wangha/Documents/NanoMQ_mirror/nng/src/core/taskq.c:287
    #5 0x71ec80 in nni_init_helper /home/wangha/Documents/NanoMQ_mirror/nng/src/core/init.c:35
    #6 0x73cd88 in nni_plat_init /home/wangha/Documents/NanoMQ_mirror/nng/src/platform/posix/posix_thread.c:422
    #7 0x71ecea in nni_init /home/wangha/Documents/NanoMQ_mirror/nng/src/core/init.c:57
    #8 0x77614b in nng_mtx_alloc /home/wangha/Documents/NanoMQ_mirror/nng/src/supplemental/util/platform.c:93
    #9 0x7ceaa7 in conf_bridge_parse_ver2 /home/wangha/Documents/NanoMQ_mirror/nng/src/supplemental/nanolib/conf_ver2.c:1200
    #10 0x7d2e56 in conf_parse_ver2 /home/wangha/Documents/NanoMQ_mirror/nng/src/supplemental/nanolib/conf_ver2.c:1728
    #11 0x704ce6 in broker_start /home/wangha/Documents/NanoMQ_mirror/nanomq/apps/broker.c:1704
    #12 0x6f9a20 in main /home/wangha/Documents/NanoMQ_mirror/nanomq/nanomq.c:142
    #13 0x7f7422e49b89 in __libc_start_call_main (/lib64/libc.so.6+0x27b89) (BuildId: f888be5f5e7d58e04cabb8c675c7ab94e77dd68c)
    #14 0x7f7422e49c4a in __libc_start_main_alias_2 (/lib64/libc.so.6+0x27c4a) (BuildId: f888be5f5e7d58e04cabb8c675c7ab94e77dd68c)
    #15 0x6b4834 in _start (/home/wangha/Documents/NanoMQ_mirror/build/nanomq/nanomq+0x6b4834) (BuildId: a6627a0d4fa780b0e2844c728518a74116e33cca)

SUMMARY: AddressSanitizer: stack-use-after-return (/lib64/libasan.so.8+0x644cb) (BuildId: 542ad02088f38edfdba9d4bfa465b2299f512d3e)
Shadow bytes around the buggy address:
  0x7f741954dd80: f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 00 00 00 00
  0x7f741954de00: f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 00 00 00 00
  0x7f741954de80: f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5
  0x7f741954df00: f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5
  0x7f741954df80: f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5
=>0x7f741954e000: f5 f5 f5 f5 f5 f5[f5]f5 f5 f5 f5 f5 00 00 00 00
  0x7f741954e080: f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5
  0x7f741954e100: f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5
  0x7f741954e180: f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 00 00 00 00
  0x7f741954e200: f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5
  0x7f741954e280: f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 00 00 00 00
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
Thread T2 created by T0 here:
    #0 0x7f7423e48956 in pthread_create (/lib64/libasan.so.8+0x48956) (BuildId: 542ad02088f38edfdba9d4bfa465b2299f512d3e)
    #1 0x73ca81 in nni_plat_thr_init /home/wangha/Documents/NanoMQ_mirror/nng/src/platform/posix/posix_thread.c:279
    #2 0x734bfe in nni_thr_init /home/wangha/Documents/NanoMQ_mirror/nng/src/core/thread.c:121
    #3 0x73eb0a in nni_posix_pollq_create /home/wangha/Documents/NanoMQ_mirror/nng/src/platform/posix/posix_pollq_epoll.c:386
    #4 0x73ebec in nni_posix_pollq_sysinit /home/wangha/Documents/NanoMQ_mirror/nng/src/platform/posix/posix_pollq_epoll.c:400
    #5 0x73ccb8 in nni_plat_init /home/wangha/Documents/NanoMQ_mirror/nng/src/platform/posix/posix_thread.c:396
    #6 0x71ecea in nni_init /home/wangha/Documents/NanoMQ_mirror/nng/src/core/init.c:57
    #7 0x77614b in nng_mtx_alloc /home/wangha/Documents/NanoMQ_mirror/nng/src/supplemental/util/platform.c:93
    #8 0x7ceaa7 in conf_bridge_parse_ver2 /home/wangha/Documents/NanoMQ_mirror/nng/src/supplemental/nanolib/conf_ver2.c:1200
    #9 0x7d2e56 in conf_parse_ver2 /home/wangha/Documents/NanoMQ_mirror/nng/src/supplemental/nanolib/conf_ver2.c:1728
    #10 0x704ce6 in broker_start /home/wangha/Documents/NanoMQ_mirror/nanomq/apps/broker.c:1704
    #11 0x6f9a20 in main /home/wangha/Documents/NanoMQ_mirror/nanomq/nanomq.c:142
    #12 0x7f7422e49b89 in __libc_start_call_main (/lib64/libc.so.6+0x27b89) (BuildId: f888be5f5e7d58e04cabb8c675c7ab94e77dd68c)
    #13 0x7f7422e49c4a in __libc_start_main_alias_2 (/lib64/libc.so.6+0x27c4a) (BuildId: f888be5f5e7d58e04cabb8c675c7ab94e77dd68c)
    #14 0x6b4834 in _start (/home/wangha/Documents/NanoMQ_mirror/build/nanomq/nanomq+0x6b4834) (BuildId: a6627a0d4fa780b0e2844c728518a74116e33cca)

==51312==ABORTING
```

**Comment by JaylinYu** [comment]
could be related to the bug we just fixed yesterday night
