### ISSUE TITLE
broker aio is already in a list

### ISSUE THREAD

**Issue by wanghaEMQ** [nanomq/NanoNNG#976]
**Describe the bug**
```
2024-06-03 11:21:05 [173410] INFO  /home/wangha/Documents/git/nanomq/nng/src/mqtt/protocol/mqtt/mqtt_quic_client.c:1069  mqtt_timer_cb: Send pingreq (sock0x51d000000fe8)(5000ms)
2024-06-03 11:21:10 [173411] INFO  /home/wangha/Documents/git/nanomq/nng/src/mqtt/protocol/mqtt/mqtt_quic_client.c:1069  mqtt_timer_cb: Send pingreq (sock0x51d000000fe8)(5000ms)
panic: /home/wangha/Documents/git/nanomq/nng/src/core/aio.c: 355: assert err: !nni_aio_list_active(
This message is indicative of a BUG.
Report this at https://github.com/emqx/nanomq
/home/wangha/Documents/git/nanomq/build/nanomq/nanomq(nni_show_backtrace+0xb4) [0x5555556a29e6]
/home/wangha/Documents/git/nanomq/build/nanomq/nanomq(nni_panic+0x1cc) [0x5555556a2cce]
/home/wangha/Documents/git/nanomq/build/nanomq/nanomq(nni_aio_begin+0x7f) [0x555555691e03]
/home/wangha/Documents/git/nanomq/build/nanomq/nanomq(+0x17c8f2) [0x5555556d08f2]
/home/wangha/Documents/git/nanomq/build/nanomq/nanomq(nni_ctx_send+0xc6) [0x5555556ab17b]
/home/wangha/Documents/git/nanomq/build/nanomq/nanomq(nng_ctx_send+0x1ba) [0x555555685a67]
/home/wangha/Documents/git/nanomq/build/nanomq/nanomq(server_cb+0x31aa) [0x55555567a738]
/home/wangha/Documents/git/nanomq/build/nanomq/nanomq(+0x15baaa) [0x5555556afaaa]
/home/wangha/Documents/git/nanomq/build/nanomq/nanomq(+0x15ccef) [0x5555556b0cef]
/home/wangha/Documents/git/nanomq/build/nanomq/nanomq(+0x16561c) [0x5555556b961c]
/usr/lib/libc.so.6(+0x8b55a) [0x7ffff72a955a]
/usr/lib/libc.so.6(+0x108a3c) [0x7ffff7326a3c]

Thread 17 "nng:task" received signal SIGABRT, Aborted.
[Switching to Thread 0x7fffdfa006c0 (LWP 173412)]
0x00007ffff72ab32c in ?? () from /usr/lib/libc.so.6
(gdb) bt
#0  0x00007ffff72ab32c in ?? () from /usr/lib/libc.so.6
#1  0x00007ffff725a6c8 in raise () from /usr/lib/libc.so.6
#2  0x00007ffff72424b8 in abort () from /usr/lib/libc.so.6
#3  0x00005555556b6ed7 in nni_plat_abort () at /home/wangha/Documents/git/nanomq/nng/src/platform/posix/posix_debug.c:23
#4  0x00005555556a2cd3 in nni_panic (fmt=0x55555599ae40 "%s: %d: assert err: %s") at /home/wangha/Documents/git/nanomq/nng/src/core/panic.c:66
#5  0x0000555555691e03 in nni_aio_begin (aio=0x515000021780) at /home/wangha/Documents/git/nanomq/nng/src/core/aio.c:355
#6  0x00005555556d08f2 in nano_ctx_send (arg=0x510000003db0, aio=0x515000021780)
at /home/wangha/Documents/git/nanomq/nng/src/sp/protocol/mqtt/nmq_mqtt.c:368
#7  0x00005555556ab17b in nni_ctx_send (ctx=0x510000003d40, aio=0x515000021780) at /home/wangha/Documents/git/nanomq/nng/src/core/socket.c:1438
#8  0x0000555555685a67 in nng_ctx_send (cid=..., aio=0x515000021780) at /home/wangha/Documents/git/nanomq/nng/src/nng.c:419
#9  0x000055555567a738 in server_cb (arg=0x50d000004f10) at /home/wangha/Documents/git/nanomq/nanomq/apps/broker.c:593
#10 0x00005555556afaaa in nni_taskq_thread (self=0x51e0000008a0) at /home/wangha/Documents/git/nanomq/nng/src/core/taskq.c:47
#11 0x00005555556b0cef in nni_thr_wrap (arg=0x51e0000008a8) at /home/wangha/Documents/git/nanomq/nng/src/core/thread.c:94
#12 0x00005555556b961c in nni_plat_thr_main (arg=0x51e0000008a8) at /home/wangha/Documents/git/nanomq/nng/src/platform/posix/posix_thread.c:266
--Type <RET> for more, q to quit, c to continue without paging--
#13 0x00007ffff72a955a in ?? () from /usr/lib/libc.so.6
#14 0x00007ffff7326a3c in ?? () from /usr/lib/libc.so.6
(gdb) up
#1  0x00007ffff725a6c8 in raise () from /usr/lib/libc.so.6
(gdb)
#2  0x00007ffff72424b8 in abort () from /usr/lib/libc.so.6
(gdb)
#3  0x00005555556b6ed7 in nni_plat_abort () at /home/wangha/Documents/git/nanomq/nng/src/platform/posix/posix_debug.c:23
23              abort();
(gdb)
#4  0x00005555556a2cd3 in nni_panic (fmt=0x55555599ae40 "%s: %d: assert err: %s") at /home/wangha/Documents/git/nanomq/nng/src/core/panic.c:66
66              nni_plat_abort();
(gdb)
#5  0x0000555555691e03 in nni_aio_begin (aio=0x515000021780) at /home/wangha/Documents/git/nanomq/nng/src/core/aio.c:355
355             NNI_ASSERT(!nni_aio_list_active(aio));
(gdb) p *aio
$1 = {a_count = 0, a_expire = 18446744073709551615, a_timeout = -1, a_result = 0, a_stop = false, a_sleep = false, a_expire_ok = false,
a_expiring = false, a_use_expire = false, a_task = {task_node = {ln_next = 0x0, ln_prev = 0x0}, task_arg = 0x50d000004f10,
task_cb = 0x55555567758e <server_cb>, task_tq = 0x510000000240, task_busy = 1629, task_prep = false, task_mtx = {mtx = {__data = {__lock = 0,
__count = 0, __owner = 0, __nusers = 0, __kind = 2, __spins = 0, __elision = 0, __list = {__prev = 0x0, __next = 0x0}},
__size = '\000' <repeats 16 times>, "\002", '\000' <repeats 22 times>, __align = 0}}, task_cv = {cv = {__data = {__wseq = {__value64 = 0,
__value32 = {__low = 0, __high = 0}}, __g1_start = {__value64 = 0, __value32 = {__low = 0, __high = 0}}, __g_refs = {0, 0}, __g_size = {0,
0}, __g1_orig_size = 0, __wrefs = 2, __g_signals = {0, 0}},
__size = '\000' <repeats 36 times>, "\002\000\000\000\000\000\000\000\000\000\000", __align = 0}, mtx = 0x5150000217d0}}, a_iov = {{
iov_buf = 0x0, iov_len = 0}, {iov_buf = 0x0, iov_len = 0}, {iov_buf = 0x0, iov_len = 0}, {iov_buf = 0x0, iov_len = 0}, {iov_buf = 0x0,
iov_len = 0}, {iov_buf = 0x0, iov_len = 0}, {iov_buf = 0x0, iov_len = 0}, {iov_buf = 0x0, iov_len = 0}}, a_nio = 0, a_msg = 0x50f002c76f70,
a_inputs = {0x0, 0x0, 0x0, 0x0}, a_outputs = {0x0, 0x0, 0x0, 0x0}, a_cancel_fn = 0x0, a_cancel_arg = 0x0, a_prov_data = 0x50d000004f38,
a_prov_node = {ln_next = 0x515000021698, ln_prev = 0x0}, a_expire_q = 0x5120000007c0, a_expire_node = {ln_next = 0x0, ln_prev = 0x0}, a_reap_node = {
rn_next = 0x0}}
```

**To Reproduce**
```
I donot know how to reproduce. This happened by accident when I run those commands.

./nanomq_cli/nanomq_cli bench pub -h 127.0.0.1 -p 1883 -t 'topic1' -c 5 -I 25 -q 1
./nanomq_cli/nanomq_cli bench pub -h xxx -p 1883 -t 'cmd/topic3' -c 20 -I 25 -q 1
/nanomq_cli/nanomq_cli sub -t fwd/topic1 -h xxx -p 1883
./nanomq_cli/nanomq_cli sub -t topic3 -h 127.0.0.1 -p 1883
```

** Environment Details **
 - NanoMQ version . nanonng commitid. e4c5a72be53f7df7b7e388f530621a47b41f1313
 - Operating system and version. archlinux.

**Comment by wanghaEMQ** [comment]
Here is the nanomq bridge configuration.

```
bridges.mqtt.emqx {
       server = "mqtt-quic://xxx:14567"
       proto_ver = 4
       username = test
       password = test
       clean_start = false
       clientid = "nanomq-bridge"
       keepalive = 10s
       backoff_max = 10s
       forwards = [
	           {
                       local_topic = "topic1"
                       remote_topic = "fwd/topic1"
               },
               {
                       local_topic = "topic2"
                       remote_topic = "fwd/topic2"
               }
       ]
       subscription = [
               {
                       remote_topic = "cmd/topic3"
                       local_topic = "topic3"
                       qos = 1
               },
               {
                       remote_topic = "cmd/topic4"
                       local_topic = "topic4"
                       qos = 2
               }
       ]
       quic_keepalive = 10s
       quic_idle_timeout = 60s
       quic_discon_timeout = 20s
       quic_handshake_timeout = 30s
       hybrid_bridging = false
       quic_multi_stream = false
       quic_qos_priority=true
       quic_0rtt=true
       qinitial_rtt_ms=700s
       parallel = 2
       max_send_queue_len = 1024
       max_recv_queue_len = 1024
}
```

**Comment by JaylinYu** [comment]
we have two options
1. remove the aio begin check
2. refactor nmq broker protocol layer and add one extra state in the app state machine, which add more ctx-switching workload,
